class ReportBuilder:
    def build_telegram_report(self, data: dict) -> str:
        if "error" in data:
            return f"⚠️ <b>Analiz Hatası:</b>\n{data['error']}"

        whois_text = ""
        if data['whois']:
            w = data['whois']
            reg = str(w.get('registrar', 'Gizli'))
            if reg == "None": reg = "Gizli"
            whois_text = (
                f"🏢 <b>Firma:</b> {reg[:25]}\n"
                f"📅 <b>Kayıt:</b> {w.get('creation_date', '-')}\n"
                f"⏳ <b>Bitiş:</b> {w.get('expiration_date', '-')}"
            )
        else:
            whois_text = "🚫 <i>Whois verisi çekilemedi.</i>"

        ssl_text = ""
        if data['ssl'] and data['ssl']['secure']:
            s = data['ssl']
            icon = "🟢" if s['days_left'] > 30 else "🔴"
            ssl_text = (
                f"{icon} <b>Sertifika:</b> {s['issuer'][:25]}\n"
                f"📅 <b>Bitiş:</b> {s['valid_until']} ({s['days_left']} gün)"
            )
        else:
            ssl_text = "❌ <b>SSL:</b> Güvenli Değil"

        seo = data['seo']
        speed_icon = "🚀" if seo['speed'] < 1.0 else "🐢"
        seo_text = (
            f"{speed_icon} <b>Tepki Süresi:</b> {seo['speed']} sn\n"
            f"🏷️ <b>Title:</b> {seo['title'][:35]}\n"
            f"📝 <b>Desc:</b> {seo['description']}\n"
            f"📌 <b>H1:</b> {seo['h1']}"
        )

        plugins_list = ""
        if data['plugins']:
            limit = 5
            p_names = [f"• {p}" for p in data['plugins'][:limit]]
            if len(data['plugins']) > limit:
                p_names.append(f"<i>...ve {len(data['plugins'])-limit} daha</i>")
            plugins_list = "\n".join(p_names)
        else:
            plugins_list = "• <i>Eklenti izi yok</i>"

        theme_info = data['theme'] if data['theme'] != "Not Detected" else "<i>Özel / Gizli</i>"

        report = (
            f"📡 <b>X-RAY FULL AUDIT RAPORU</b>\n"
            f"🔗 <b>Hedef:</b> <code>{data['domain'].upper()}</code>\n"
            f"➖➖➖➖➖➖➖➖➖➖\n\n"
            f"🌍 <b>DOMAIN BİLGİLERİ</b>\n"
            f"{whois_text}\n\n"
            f"⚡ <b>PERFORMANS & SEO</b>\n"
            f"{seo_text}\n\n"
            f"🔒 <b>GÜVENLİK</b>\n"
            f"{ssl_text}\n"
            f"🛡️ <b>Koruma:</b> {', '.join(data['security'])}\n\n"
            f"🏗️ <b>TEKNİK ALTYAPI</b>\n"
            f"🖥️ <b>Server:</b> {data['server']}\n"
            f"⚙️ <b>Sistem:</b> {data['cms']}\n"
            f"🎨 <b>Tema:</b> {theme_info}\n\n"
            f"🔌 <b>TESPİT EDİLEN EKLENTİLER</b>\n"
            f"{plugins_list}\n\n"
            f"➖➖➖➖➖➖➖➖➖➖\n"
            f"🤖 <i>Generated by JACKON</i>"
        )
        return report